Altinn/altinn-platform

.github/workflows/assign-issue-to-project.yml
tests/Postman/.gitignore
tests/Postman/README.md
tests/Postman/altinn3.postman_environment.json
tests/Postman/collections/App.postman_collection.json
tests/Postman/collections/Local-Test.postman_collection.json
tests/Postman/collections/Negative_Tests_Storage_and_App.postman_collection.json
tests/Postman/collections/Organization.postman_collection.json
tests/Postman/collections/Platform.postman_collection.json
tests/Postman/collections/Storage.postman_collection.json

moved postman tests from studio repo

included postman tests from studio repo

---

.github/workflows/build-and-analyze-models.yml
Altinn.Platform.Models/test/Altinn.Platform.Models.Tests/Altinn.Platform.Models.Tests.csproj

Consideration: do we really need code analysis for this project or would it be enough to build and run unit tests? 
- #391

Build and analysis workflow for platform models

---

.github/workflows/efm-ip-use-case.yml
tests/k6/docker-compose.yml
tests/k6/readme.md
tests/k6/src/api/integrationPoint.js
tests/k6/src/apiHelpers.js
tests/k6/src/config.js
tests/k6/src/errorhandler.js
tests/k6/src/tests/eformidling.js

Use case test set up for eformidling and workflow to run every 15 mins towards tt and prod.
- #557

added k6 tests + workflow for efm

---

Altinn.Platform.Models/src/Profile/Models/UserProfile.cs
Altinn.Platform.Models/src/Register/Models/Party.cs

Added new Property to Party and UserProfile for holding UUID.

---

Altinn.Platform.Models/src/Altinn.Platform.Models.csproj

NuGet Push is not automated so we need to update project properties.

Bump version to prepare for next release

---

tests/k6/src/tests/eformidling.js

Updated k6 test case description for eformidling test.

More clear error message for test

---

Altinn.Platform.Models/src/Altinn.Platform.Models.csproj
Altinn.Platform.Models/src/Register/Models/PartyName.cs
Altinn.Platform.Models/src/Register/Models/PartyNamesLookup.cs
Altinn.Platform.Models/src/Register/Models/PartyNamesLookupResult.cs

This adds the models required by https://github.com/Altinn/altinn-register/pull/169
- https://github.com/digdir/dialogporten/issues/321

Add models for party name lookups

---

.github/workflows/publish-release.yml
Altinn.Platform.Models/src/Altinn.Platform.Models.csproj
Altinn.Platform.Models/src/Directory.Build.props
Altinn.Platform.Models/src/Directory.Build.targets

Implementation of automate generation and release of NuGet for `Altinn.Platform.Models`
Automated the NuGet package generation and release process following [this guideline](https://docs.altinn.studio/community/contributing/handbook/back-end/nuget-package/).
- #666

#666 Implementation of automate generation and release of NuGet for `Altinn.Platform.Models`

---

.github/workflows/publish-release.yml

Changing directory before restore command
- #666

#666 Changing directory before restore command

---

.github/workflows/publish-release.yml

Push to NuGet repo command added
- #666

#666 Push to NuGet repo command added

---

.github/workflows/publish-release.yml
Altinn.Platform.Models/src/Directory.Build.props
Altinn.Platform.Models/src/Directory.Build.targets
Altinn.Platform.Models/stylecop.json

Patching and fixes
Temporarily removed publish step to freely do some testing.

Patching and fixes

---

.github/workflows/publish-release.yml

Add back the temporarily removed dotnet nuget push command

Add back nuget push command

---

rfcs/0000-pull-based-cd.md
rfcs/0000-template.md

Introducing a RFC for pull based CD
- #{issue number}

[RFC]: propose pull based CD

---

products.yaml

Testing infra products TF tooling
- #{issue number}

[infra/products]: Add altinn-receipt

---

.github/workflows/products-deploy.yml
infrastructure/products/azure_arm.tf

ABAC role assigment is done after app should have received permission.

update apps permission

---

products.yaml

remove federation for altinn access management

---

.github/workflows/daisctl-release.yml

chore(daisctl): update daisctl-release.yml

---

.github/workflows/daisctl-release.yml

chore(daisctl): fix workdir in release

---

products.yaml

Create the Product Altinn App. APP as slug as PAA was already taken.
- #858

Add apps as a product

---

actions/terraform/plan/action.yaml

Change from bash to github-script for terraform plan summary

---

actions/terraform/plan/action.yaml

Order seems to be important in workflow

---

products.yaml

- https://github.com/Altinn/altinn-platform/issues/864
- https://github.com/Altinn/altinn-access-management/issues/792

add altinn-access-management to products.yaml

---

renovate.json

Update the go.mod file after renovate is done updating dependencies. This might result in changes to go.mod when terraform is updated, but shouldn't be a problem.
- #{issue number}

Instruct renovate to run go mod tidy

---

CODEOWNERS

Make the github team codeowners

---

rfcs/0000-self-hosted-github-runners.md

Updates after team had a walkthrough of the RFC yesterday.
- #861

Update self-hosted runners RFC after team discussion

---

infrastructure/products/entra.tf
products.yaml

Fix bug when federated credentials are set to lower

---

.github/workflows/products-deploy.yml
infrastructure/products/azure_arm.tf
infrastructure/products/entra.tf

Make it possible to run plan with self review from PR

---

.github/workflows/products-deploy.yml
infrastructure/products/azure_arm.tf

Do we need to use the same app for both plan and apply when we are running from main?
- #{issue number}

Switch to using reader environment for plan step

---

infrastructure/products/azure_arm.tf

Grant listKeys/action to reader group
Seems like the reader group needs more rights on the App Configuration resource

Feat(#956): Improve workflow feedback

---

.github/workflows/gh-runner-pr.yml
.github/workflows/gh-runner-release.yml
infrastructure/images/gh-runner/Dockerfile
infrastructure/images/gh-runner/README.md
infrastructure/images/gh-runner/scripts/app-token.sh
infrastructure/images/gh-runner/scripts/entrypoint.sh
infrastructure/images/gh-runner/scripts/token.sh

Docker image that is to be used for self-hosted runners.
Partially fixes #861

Docker image for self-hosted runners

---

.github/DISCUSSION_TEMPLATE/request-for-comments.yml

Create a template for discussion category rfc based on the template in our repo
An example of the result can be viewed in my repo [here](https://github.com/tjololo/hello-actions/discussions/categories/request-for-comments).
Click ["New Discussion"](https://github.com/tjololo/hello-actions/discussions/new?category=request-for-comments) to see an example of it when filing a new discussion. 
View a resulting discussion [here](https://github.com/tjololo/hello-actions/discussions/8)

Create request-for-comments template

---

.github/workflows/altinn-monitor-test-rg-deploy.yml
.github/workflows/products-deploy.yml
infrastructure/adminservices-test/altinn-monitor-test-rg/data.tf
infrastructure/adminservices-test/altinn-monitor-test-rg/grafana.tf
infrastructure/adminservices-test/altinn-monitor-test-rg/prometheus.tf
infrastructure/adminservices-test/altinn-monitor-test-rg/providers.tf
infrastructure/adminservices-test/altinn-monitor-test-rg/rg.tf

iac test central monitoring

---

infrastructure/products/azure_arm.tf

Terraform reader sp need AKS cluster user role to read cluster
https://learn.microsoft.com/en-us/azure/aks/control-kubeconfig-access#available-permissions-for-cluster-roles
- #411

Add reader to aks cl user role

---

.github/workflows/altinncr-deploy.yml
infrastructure/adminservices-prod/altinncr/acr.tf
infrastructure/adminservices-prod/altinncr/data.tf
infrastructure/adminservices-prod/altinncr/kv.tf
infrastructure/adminservices-prod/altinncr/providers.tf
infrastructure/adminservices-prod/altinncr/terraform.tfvars
infrastructure/adminservices-prod/altinncr/variables.tf

Add containerregistry for pull-through cache.
- #559

Add code deployed altinncr

---

.github/workflows/grafana-annotation.yml

chore: add grafana annotation workflow

---

infrastructure/products/terraform.tfvars

chore: add a grafana env to tf vars

---

.github/workflows/grafana-annotation.yml

chore(workflows): add contents write to grafana

---

.github/workflows/grafana-annotation.yml

chore(ci): fix create_grafana_key in workflow

---

.github/workflows/grafana-annotation.yml

chore(ci): use service account to auth to grafana

---

.github/workflows/grafana-annotation.yml

chore(ci): fix timestamp in grafana annotation

---

.github/workflows/grafana-annotation.yml

chore(ci): update grafana-annotation.yml

---

.github/workflows/grafana-annotation.yml

chore(ci): use better tags in grafana annotations

---

infrastructure/adminservices-test/altinn-monitor-test-rg/appinsights.tf
infrastructure/adminservices-test/altinn-monitor-test-rg/grafana.tf
infrastructure/adminservices-test/altinn-monitor-test-rg/law.tf

feat(grafana): be able to query traces/logs

---

infrastructure/adminservices-test/altinn-monitor-test-rg/grafana.tf

fix(grafana): use principalId in LAW role

---

infrastructure/adminservices-test/altinn-monitor-test-rg/grafana.tf

fix(altinn-monitor-test): add read role for grafana

---

.github/workflows/build-and-release-send-ci-cd-trace-action.yml
.github/workflows/grafana-annotation.yml
actions/send-ci-cd-trace/.gitignore
actions/send-ci-cd-trace/action.yml
actions/send-ci-cd-trace/package-lock.json
actions/send-ci-cd-trace/package.json
actions/send-ci-cd-trace/src/index.ts
actions/send-ci-cd-trace/tsconfig.json

This action should be ready to be used by other teams as well
- #1047

feat(actions): use otel to push gh data 

---

.github/workflows/build-and-release-send-ci-cd-trace-action.yml

chore(workflows): update build-and-release-send-ci-cd-trace-action.yml

---

actions/send-ci-cd-trace/package-lock.json
actions/send-ci-cd-trace/package.json
actions/send-ci-cd-trace/tsconfig.json

fix(actions): make send cicd trace use a bundle in dist

---

rfcs/0000-operator-managed-apim-config.md

First version of rfc after github discussion: https://github.com/Altinn/altinn-platform/discussions/986

rfc: operator managed apim configuration

---

actions/send-ci-cd-trace/action.yml
actions/send-ci-cd-trace/src/index.ts

fix(actions/traces): add check for params and log traceId

---

infrastructure/adminservices-test/altinn-monitor-test-rg/grafana.tf

fix(admin-test): add altinn devs to grafana

---

actions/send-ci-cd-trace/package-lock.json
actions/send-ci-cd-trace/package.json
actions/send-ci-cd-trace/src/index.ts

fix(trace-action): remove azidentity

---

actions/send-ci-cd-trace/src/index.ts

fix(tracer-action): log possible errors when sending spans

---

.github/workflows/grafana-annotation.yml
actions/send-ci-cd-trace/src/index.ts

chore(ci): update send annotation workflow

---

actions/send-ci-cd-trace/src/index.ts

fix(traces-action): shutdown only once

---

.github/workflows/daisctl-pr.yml

Only run daisctl pipeline when files that changes daisctl is changed

fix: only run pipeline when files in daisctl has changed

---

actions/send-ci-cd-trace/src/index.ts

fix(tracer-action): do not force flush

---

actions/send-ci-cd-trace/package-lock.json
actions/send-ci-cd-trace/package.json
actions/send-ci-cd-trace/src/index.ts

fix(traces-action): remove batchspanProcessor

---

actions/send-ci-cd-trace/src/index.ts

fix(ci-tracer): extend timeout before exporting

---

actions/send-ci-cd-trace/src/index.ts

fix(ci-tracer): handle errors inside of run func

---

infrastructure/adminservices-test/altinn-monitor-test-rg/k6_tests_rg_k6_operator.tf

Deploy the k6 operator

---

products.yaml

feat: add digitalt dodsbo as product

---

rfcs/0004-container-runtime-workload-identity.md

rfc: container runtime workload identity

---

.github/workflows/release-flux-artifact.yml

Remove trailing whitespace from flux tag command

---

.github/workflows/release-flux-artifact.yml

fix: another error in bash script

---

infrastructure/modules/aks-resources/grafana-operator.tf

Move EXTERNAL_GRAFANA_URL to post-deploy kustomization where it's actually needed.

fix: Move GRAFANA_ADMIN_APIKEY substitution to post-deploy

---

flux/linkerd/post-deploy/rollout-restart-job.yaml

fix: Add list permission to deployment restart role

---

.github/workflows/manage-flux-releases.yml

fix: change metrix gen to per release not release-env

---

actions/terraform/init/action.yaml

@tjololo, is the renovate config working as intended?

chore: bump default terraform version to 1.12.2

---

actions/generate-k6-manifests/action.yml
actions/generate-k6-manifests/cmd/expected_generated_files/v1/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v10/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v10/prod/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v10/tt02/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v10/yt01/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v11/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v2/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v3/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v4/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v5/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v5/yt01/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v6/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v6/yt01/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v7/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v8/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/expected_generated_files/v9/at22/testrun.json.tmpl
actions/generate-k6-manifests/cmd/generator.go
actions/generate-k6-manifests/test_service/conf.yaml
infrastructure/images/k6-action/jsonnet/main.jsonnet

Minor tweaks
- fix typo in action.yml
- add a tag with the test name
- link to grafana dashboard
- allow dashboard variable to be tweak, it's useful for testing.
- add --server-side to apply command to bypass limitation with annotations size
- add command to abort tests

chore: minor tweaks

---

actions/terraform/write-terraform-summary/action.yaml

chore: fix code scanning warning in write-terraform-summary action

---

infrastructure/adminservices-prod/altinncr/iam.tf

fix(acr): grant to correct principal
